# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-03-25 19:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('getdata', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GetLesson',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lesson_name', models.TextField(default=None)),
                ('lesson_date', models.DateField(default=None)),
                ('lesson_time', models.TimeField(default=None)),
                ('lesson_location', models.TextField(default=None)),
                ('lessons_comments', models.TextField(default=None)),
            ],
        ),
    ]
