# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-03-25 19:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('getdata', '0002_getlesson'),
    ]

    operations = [
        migrations.RenameField(
            model_name='getlesson',
            old_name='lessons_comments',
            new_name='lesson_comments',
        ),
    ]
