# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-03-29 19:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('getdata', '0003_auto_20170325_1933'),
    ]

    operations = [
        migrations.CreateModel(
            name='GetLocation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.TextField(default=None)),
                ('coordinates', models.TextField(default=None)),
            ],
        ),
        migrations.AlterField(
            model_name='getclient',
            name='driver_no',
            field=models.TextField(default=None, max_length=5),
        ),
        migrations.AlterField(
            model_name='getclient',
            name='log_no',
            field=models.TextField(default=None, max_length=9),
        ),
        migrations.AlterField(
            model_name='getclient',
            name='no_of_lessons',
            field=models.CharField(default=None, max_length=3),
        ),
    ]
