# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-04-05 20:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('getdata', '0004_auto_20170329_2046'),
    ]

    operations = [
        migrations.AddField(
            model_name='getlocation',
            name='x',
            field=models.CharField(default=None, max_length=30),
        ),
        migrations.AddField(
            model_name='getlocation',
            name='y',
            field=models.CharField(default=None, max_length=30),
        ),
    ]
