# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-13 22:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('getdata', '0007_delete_getexpenses'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='getlocation',
            name='x',
        ),
        migrations.RemoveField(
            model_name='getlocation',
            name='y',
        ),
    ]
