# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-14 17:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('getdata', '0009_auto_20170414_0005'),
    ]

    operations = [
        migrations.CreateModel(
            name='GetUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.TextField(default=None)),
                ('password', models.TextField(default=None)),
            ],
        ),
        migrations.DeleteModel(
            name='GetExpenses',
        ),
    ]
