# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-14 17:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('getdata', '0011_auto_20170414_1826'),
    ]

    operations = [
        migrations.CreateModel(
            name='GetExpenses',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expense_name', models.TextField(default=None)),
                ('expense_amount', models.CharField(default=None, max_length=6)),
                ('expense_date', models.DateField(default=None)),
            ],
        ),
        migrations.RenameField(
            model_name='getlocation',
            old_name='location_name',
            new_name='coordinates',
        ),
        migrations.RenameField(
            model_name='getlocation',
            old_name='location_type',
            new_name='type',
        ),
        migrations.RemoveField(
            model_name='getlocation',
            name='location_x',
        ),
        migrations.RemoveField(
            model_name='getlocation',
            name='location_y',
        ),
        migrations.AddField(
            model_name='getlocation',
            name='x',
            field=models.CharField(default=None, max_length=30),
        ),
        migrations.AddField(
            model_name='getlocation',
            name='y',
            field=models.CharField(default=None, max_length=30),
        ),
    ]
