# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-17 11:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('getdata', '0012_auto_20170414_1831'),
    ]

    operations = [
        migrations.RenameField(
            model_name='getlocation',
            old_name='coordinates',
            new_name='location_detail',
        ),
        migrations.RenameField(
            model_name='getlocation',
            old_name='type',
            new_name='location_type',
        ),
        migrations.RenameField(
            model_name='getlocation',
            old_name='x',
            new_name='location_x',
        ),
        migrations.RenameField(
            model_name='getlocation',
            old_name='y',
            new_name='location_y',
        ),
    ]
